### ISSUE TITLE
Graph implementation using C++, Python

### ISSUE THREAD

**Issue by py93** [jainaman224/Algo_Ds_Notes#1025]
I wanted to contribute by adding simple graph implementation using C++, Python and Java for the Javascript version which exists.

**Comment by shahkv95** [comment]
@jainaman224 I would like to take up this issue.

NOTE : I would request you to allow me to work on multiple issues before GSSoC ends. Because I am available for full day. And wish to make a score more than 150 at least. Because I was busy regarding a research paper publication, so couldn't contribute last month. I am sure you understand it and allow me to contribute as much as I can. Thank you @jainaman224

**Comment by py93** [comment]
@jainaman224 I am done with C++ and Python. Just need to finish off Java implementation.
Will raise the PR by tonight.

**Comment by py93** [comment]
@jainaman224 Raised a PR.
