### ISSUE TITLE
Reversal of linked list

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#154]
Reverse a linked list
- [ ] Iteratively
- [ ] Recursively

**Comment by adishjain** [comment]
On it! 
JAVA

**Comment by richa-coder** [comment]
Can i write in python or C?

**Comment by adishjain** [comment]
@richa-coder Yes! Please proceed with whichever language you feel comfortable in.

**Comment by sahilrider** [comment]
I pulled a request on this issue using C.

**Comment by jainaman224** [comment]
@richa-coder it will be better if you work in python.
If you haven't started yet. Can I merge pull request in C.

**Comment by sahilrider** [comment]
@jainaman224 Mine PR is accepted? I am a newbie ,so plz help me.

**Comment by richa-coder** [comment]
My PR is in python.



[image: --]

Richa Singh
[image: https://]about.me/richa-singh
<https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by richa-coder** [comment]
hey Aman,My PR is in python.



[image: --]

Richa Singh
[image: https://]about.me/richa-singh
<https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by adishjain** [comment]
@sahilrider Yes! It has been merged

**Comment by jainaman224** [comment]
Can you please communicate with us on gitter regarding help. It will be better. https://gitter.im/Algo_Ds_Notes/Algo_Ds_Notes

**Comment by jainaman224** [comment]
@richa-coder Thank you. Please file a PR once you are completed with it.

**Comment by mastash3ff** [comment]
#227

**Comment by mrwonko** [comment]
I'm interested in implementing this in C++. However I'm not exactly clear on the requirements - if it's just "implement a linked list & reversing it in C++", the C implementation technically already fulfills that. (Well, it's only an iterative implementation, no recursive one.)

I'll do an implementation showcasing in what I consider "modern C++" showcasing the differences to C. I'll put particular emphasis on move semantics (and zero-overhead abstractions in general).

It would also be useful for the linked list to implement the [container concept](http://en.cppreference.com/w/cpp/concept/Container) to showcase integration in the standard library (to allow using the standard algorithms on it), although that would make the code quite complex since it requires also writing an iterator, and using ready-made algorithms somewhat defeats the purpose of showing how to implement them.

I'll split it into multiple commits so we can discuss it and only add parts of it.

How are unit tests done in this project? Data structures really lend themselves to automated testing.

**Comment by PiyushGoyal443** [comment]
can i work in c++ for this?
