### ISSUE TITLE
Sum of Digits in JS.

### ISSUE THREAD

**Issue by JanaSabuj** [jainaman224/Algo_Ds_Notes#1610]
I would like to implement this problem in JavaScript. (GSSoc20)

**Comment by abhinashgiri** [comment]
I would love to work on this as a part of GSSoc 20. Please assign me if possible.

**Comment by RiaJha02** [comment]
Approach1: Take the number as the string and then split it. Now, we will create an array wherein we'll be getting the digits since we need to use the reduce() method which will further execute a reducer function to provide an answer in a single value.
Approach2: Take the number and a result variable (initialised it with zero) to store the answer. Now take the remainder of 10 with the number and add it to the result, then the number will be divided by 10 and continue till the number becomes zero.
