### ISSUE TITLE
Square Root Decomposition 

### ISSUE THREAD

**Issue by kaustubh-pandey** [jainaman224/Algo_Ds_Notes#562]
I wanted to add square root decomposition algorithm example for finding sum of numbers in a given range in C++ and Python. Can I work on this?

**Comment by rishabhgarg25699** [comment]
@kaustubh-pandey  Square Root Decomposition is the important topic and hard topic and is very famous for competitive programming competitions and it is achieved by more than 1 method. Please specify by which method you have to do and also please comment your code so that reader can easily understand your code.
I have a suggestion If you have any doubt in this topic you can refer the video from Anudeep Nekkanti in You tube . He is one of the best codes of the India.

**Comment by kaustubh-pandey** [comment]
I want to apply this method for finding sum of numbers in a given range(the same shown in video of Anudeep Nekkanti)
